blank_issues_enabled: false
contact_links:
  - name: Security Report
    url: https://github.com/brettstark/saas-starter-template/security/policy
    about: Please report security vulnerabilities privately.
